### ISSUE TITLE
Error installation on Ubuntu

### ISSUE THREAD

**Issue by ghost** [mozvip/Sick-Beard#104]
Hi,

there is an error message when installing on Ubuntu :
Error in AddSubtitlesSupport: table episode_links already exists
Traceback (most recent call last):
  File "/root/.sickbeard/SickBeard.py", line 356, in <module>
    main()
  File "/root/.sickbeard/SickBeard.py", line 276, in main
    sickbeard.initialize(consoleLogging=consoleLogging)
  File "/root/.sickbeard/sickbeard/**init**.py", line 849, in initialize
    db.upgradeDatabase(db.DBConnection(), mainDB.InitialSchema)
  File "/root/.sickbeard/sickbeard/db.py", line 204, in upgradeDatabase
    _processUpgrade(connection, schema)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 224, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/root/.sickbeard/sickbeard/db.py", line 215, in _processUpgrade
    instance.execute()
  File "/root/.sickbeard/sickbeard/databases/mainDB.py", line 707, in execute
    self.connection.action("CREATE TABLE episode_links (episode_id INTEGER, link                                                                                                                                                              TEXT)")
  File "/root/.sickbeard/sickbeard/db.py", line 127, in action
    sqlResult = self.connection.execute(query)
sqlite3.OperationalError: table episode_links already exists

Thanks,

**Comment by an0Nym0us63** [comment]
just remove your sickeard.db and test please

**Comment by Antechris** [comment]
Hi,
I have the same error (table episode_links already exists) but on my Synology DS1512.

Remove sickbeard.db don't change anything. :(

**Comment by ghost** [comment]
There is no sickbeard.db already on the system !
Ubuntu install is fresh and it's the first sickbeard install !

**Comment by an0Nym0us63** [comment]
ok ill try an improved hack
