### ISSUE TITLE
500 Internal Server Error when accessing to log

### ISSUE THREAD

**Issue by chrispo8174** [mozvip/Sick-Beard#159]
hello,

i can acces "view log errors" but not the "view log" ; i got the following message 

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "D:\SOFTWARES\Sickbeard\Sick-Beard-development\cherrypy_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "D:\SOFTWARES\Sickbeard\Sick-Beard-development\cherrypy\lib\encoding.py", line 193, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "D:\SOFTWARES\Sickbeard\Sick-Beard-development\cherrypy_cpdispatch.py", line 25, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "D:\SOFTWARES\Sickbeard\Sick-Beard-development\sickbeard\webserve.py", line 2592, in viewlog
    x = x.decode('utf-8')
  File "D:\PROGRAMMES\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 1: invalid continuation byte

Powered by CherryPy 3.2.0rc1 

thanks for your answer (and sorrt for my english !)

chris

**Comment by chrispo8174** [comment]
bonjour et bonne année !!

la derniere mise a jour a resolu ce problème...

merci beaucoup !
