### ISSUE TITLE
Bug série ajoutée via une appli mobile

### ISSUE THREAD

**Issue by YanK-fr** [mozvip/Sick-Beard#71]
Bonjour,

J'ai ajouté une série via "couch forwarder free" résultat je pense qu'il y a eu un soucis sur la série au niveau de la langue car j'ai l'erreur suivante.
Y a t-il un moyen de supprimer une série ou d'accéder à la base de données pour modifier ça ?

Erreur :

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2682, in displayShow
    return _munge(t)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 128, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_usr_local_sickbeard_custom_var_SickBeard_data_interfaces_default_displayShow_tmpl.py", line 399, in respond
ValueError: invalid literal for int() with base 10: 'en'

**Comment by YanK-fr** [comment]
C'est bon un coup de delete avec le "mass update" et c'est bon. J'ai rajouté à la série à la main.
Du coup faire attention avec quoi on ajoute des séries dans la liste

**Comment by an0Nym0us63** [comment]
Alors nous ne supportons pas les applis mobiles car aucune ne gere nos modifications. Tu peux soit editer le show pour lui reattribuer une langue si tu peux.  Sinon seul solution editer manuellement le fichier sickbeard.db avec un editeur de bdd  ou tout simplement supprimer ce fichier et rescanner du debut

---

De: Yannick KERMAREC 
Envoyé: mar., 23/04/2013 23:36
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
Objet: [Sick-Beard] Bug série ajoutée via une appli mobile (#71)

**Comment by YanK-fr** [comment]
Ok merci. ;)
