### ISSUE TITLE
Erreur lors de l'ajout d'une nouvelle série après MàJ d'aujourd'hui

### ISSUE THREAD

**Issue by lpnsk** [mozvip/Sick-Beard#84]
Bonjour, 

Lors de l'ajout d'une nouvelle série, le message suivant apparaît dans la log et la série n'est pas ajoutée : 

[2013-05-15 14:45:33.138960 SHOWQUEUE-ADD :: Error trying to add show: Invalid language 1, options are: ['da', 'fi', 'nl', 'de', 'it', 'es', 'fr', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'zh', 'cs', 'sl', 'hr', 'ko', 'en', 'sv', 'no']

Testé avec série existante et nouvelle série sur 2 syno différents qui avaient un fonctionnement normal avant la mise à jour.

Merci !

**Comment by an0Nym0us63** [comment]
ok je test ce soir

**Comment by lpnsk** [comment]
Infos complémentaires : 
- Si je décoche "subtitle search" dans les subtitles settings et que je cherche à ajouter un show, le show est bien ajouté.
- Si je le laisse coché sans inclure de langue et que je cherche à ajouter un show, l'erreur revient
- Si j'ajoute le show (coche vide) puis coche la recherche de sub et essaie d'afficher la fiche du show ajouté, erreur 500 sur le navigateur : 

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 2705, in displayShow
    return _munge(t)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 128, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/usr/local/python/lib/python2.7/site-packages/Cheetah/Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_usr_local_sickbeard_custom_var_SickBeard_data_interfaces_default_displayShow_tmpl.py", line 399, in respond
ValueError: invalid literal for int() with base 10: 'en'
- Si je re-décoche la recherche de sub, je peux à nouveau afficher la fiche de la série.

Je pense que ça aide à mieux cibler le problème =)

Et merci  !

**Comment by an0Nym0us63** [comment]
Merci mais jai trouvé lerreur faut juste que je rentre pour pouvoir colmmiter merci pour les infos

---

De: lpnsk 
Envoyé: mer., 15/05/2013 18:17
A: mozvip/Sick-Beard Sick-Beard@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [Sick-Beard] Erreur lors de l'ajout d'une nouvelle série après MàJ d'aujourd'hui (#84)

**Comment by an0Nym0us63** [comment]
corrigé ;)
